### ISSUE TITLE
Tracking screen on multiples pages

### ISSUE THREAD

**Issue by 2803media** [danwilson/google-analytics-plugin#129]
Hi, in my phonegap app I have the following architecture:

-index.html
-page1.html
-page2.html
...

I add this to the index.html:

    <script>       
        document.addEventListener("deviceready", onDeviceReady, false);
        
        function onDeviceReady() {
            window.analytics.startTrackerWithId('UA-1233455-1');
            window.analytics.trackView('Home');
        }  
    </script>

And this to the other pages:

    <script>       
            window.analytics.trackView('page1');
    </script>

In GA I only saw the 'Home' screen and don't see other screens. Do I miss something or do this plugin don't work with multiple pages architecture?
Thanks

**Comment by danwilson** [comment]
I'm not sure how it would work with multiple pages. I would guess that the way Cordova plugins work depend on it being single page, since it adds the property on launch to the window object.  It would only do that once and then future screens would no longer have that reference.

Were there any console logs in Safari/Chrome Dev tools? (I know this is old, sorry for the late followup)

**Comment by victorsosa** [comment]
I recommend you to set this code on the routing methods of the app and not in the page itself.

**Comment by victorsosa** [comment]
I tested this out in the last version and it is working.

**Comment by pallaviMN** [comment]
@danwilson , how can i get Analytics activity feed log ?

Regards
Pallavi M N

**Comment by victorsosa** [comment]
this is too old, issue closed
