### ISSUE TITLE
$cordovaGoogleAnalytics becomes undefined in browser only AFTER function invocation

### ISSUE THREAD

**Issue by acoard** [danwilson/google-analytics-plugin#162]
Hi all,

So, to be clear, I'm using Ionic and installed the analytics plugin from [this ngCordova page](http://ngcordova.com/docs/plugins/googleAnalytics/).  Just let me know if this is considered a separate project and I'll happily take this issue down.

From reading [threads like this](https://github.com/danwilson/google-analytics-plugin/issues/107) I realize that $cordovaGoogleAnalytics is not supposed to be defined when debugging in the browser. And this issue happens when I'm in the browser (have yet to test on a device yet, as this issue is a show-stopper).

Now onto the problem:

    if (typeof $cordovaGoogleAnalytics !== 'undefined'){
      //we get in this conditional when in Chrome
      
      // this will log out an object with all the tracking methods you'd expect
      console.log('Analytics is defined', $cordovaGoogleAnalytics);
      
      //this will log out the method in question I've been trying to use with no issue
      // console.log($cordovaGoogleAnalytics.startTrackerWithId)
      
      //running this command leads to "Uncaught TypeError: Cannot read property 'startTrackerWithId' of undefined"
      $cordovaGoogleAnalytics.startTrackerWithId();
     
      //at this point, $cordovaGoogleAnalytics is undefined
      console.log('is it still defined?', $cordovaGoogleAnalytics);
    }

If I do something like `window.test = $cordovaGoogleAnalytics.startTrackerWithId` and then call `test()` in the browser at a later time I get the same error.  If I comment out `$cordovaGoogleAnalytics.startTrackerWithId();` then in the final console.log it still will be defined.

The above code is in the `app.run()` section of my Angular app, and everything is wrapped in `$ionicPlatform.ready` which should be functionally equivalent to a device ready event.

A solution could be either of the following:
1. Have the analytics plugin be undefined from the beginning in the browser, and thus the browser should never get into the above `if` statement.
2. Have the analytics plugin stay defined the whole time.  I don't mind if analytics is kept on in the browser / dev, I can handle that myself.

Any help would be appreciated because this is a weird one.  Oh, and of course thanks for taking the time not just to create such a useful plugin, but also for reading this question. Thanks!

**Comment by danwilson** [comment]
The ngCordova piece is built by others on top of this plugin, so I can't answer specifically for that.

The one thing that is different from what you mentioned and what was in #107 is what you are testing.  I'm not sure what $cordovaGoogleAnalytics actually contains, but this plugin specifically creates an object `window.analytics` that is used (in some form) by $cordovaGoogleAnalytics.  So in browser, I'd suspect you wouldn't even enter the if condition with `if (typeof window.analytics !== 'undefined'){`

The other weirdness might be stemming from trying to use that, and since `$.startTrackerId` presumably tried to do an action on `window.analytics` it might be tripping up there, causing the future undefineds.

So try:
`if (typeof window.analytics !== 'undefined'){`
and see if that keeps you from entering... and then try on device/simulator to see if everything works as expected from there.

**Comment by victorsosa** [comment]
this is most likely to be a ngCordova issue.

**Comment by victorsosa** [comment]
please check issue #27 if you are using ionic

**Comment by victorsosa** [comment]
please try the answer #290
