### ISSUE TITLE
Getting libGoogleAnalyticsServices.jar

### ISSUE THREAD

**Issue by femiji** [danwilson/google-analytics-plugin#176]
Where do you get the libGoogleAnalyticsServices.jar from?

I have Google Play Service installed.

**Comment by EMCP** [comment]
It's not clear if I need to use the Android SDK manager on my ionic project or .. or just install the google play services in general.

I have the jar file now , trying to figure out where to add it to the ionic project so that it gets integrated properly...  do i drop it in `~/resources/android`

**Comment by danwilson** [comment]
libGoogleAnalyticsServices.jar is not used by the project in the current versions.

**Comment by EMCP** [comment]
@danwilson understood.  Then I need to figure out why my `window.analytics` is still undefined

**Comment by muzaheed57** [comment]
@danwilson because of "libGoogleAnalyticsServices.jar" my build is getting failed. and showing "unable to convert dex ....".
removing "libGoogleAnalyticsServices.jar" fixes the problem.
on the other side google analystics stopped working!!!!!!!!!!!

so how you are so sure about :

> libGoogleAnalyticsServices.jar is not used by the project in the current versions.

can u plz explain?
after your confirmation i will start to investigate on  other parts .
thanks

**Comment by victorsosa** [comment]
libGoogleAnalyticsServices.jar is not used by the project.
