### ISSUE TITLE
Unable to work together with admob plugin

### ISSUE THREAD

**Issue by fobus42** [danwilson/google-analytics-plugin#262]
Hi,

Bot this and admob (https://github.com/admob-google/admob-cordova) plugin works good if they are not installed together. But When I'm installing them together I'm getting this error.

` Manifest merger failed : Attribute meta-data#com.google.android.gms.version@value value=(8115000) from AndroidManifest.xml:12:66-89

        is also present at [com.google.android.gms:play-services-basement:9.4.0] AndroidManifest.xml:23:13-66 value=(@integer/google_play_services_version).

        Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:12:9-92 to override.
`

How can I fix it?

**Comment by victorsosa** [comment]
They should fix the metadata tag, please read this article 
https://stackoverflow.com/questions/19724113/google-play-services-update

Because they including the jars directly instead of via Gradle's Dependency Management logic. 
```
<source-file src="src/android/libs/admobadplugin.jar" target-dir="libs/"/>
<source-file src="src/android/libs/google-play-services.jar" target-dir="libs/"/>

```
This line need to be changed:
`<meta-data android:name="com.google.android.gms.version" android:value="8115000"/>`
https://github.com/admob-google/admob-cordova/blob/master/plugin.xml#L28

We don't have to change anything here.

**Comment by fobus42** [comment]
@victorsosa  yes you are right, this is their problem. Thank you!

**Comment by victorsosa** [comment]
you welcome
