### ISSUE TITLE
Can we send crash reports to GA?

### ISSUE THREAD

**Issue by malwatte** [danwilson/google-analytics-plugin#310]
Can we send crash reports to GA?
Thanks

**Comment by victorsosa** [comment]
Yes, you can do it this way.
`
window.ga.trackException('Description', Fatal) `where Fatal is boolean

**Comment by malwatte** [comment]
Thank you. I'll give it a try.

**Comment by malwatte** [comment]
@victorsosa ,
I force crashed iOS app. But no crash reports showing up in Google Analytics. I checked crash reports in the device itself and there were few. I have enabled window.ga.enableUncaughtExceptionReporting as well.
Am I doing it wrong?

(window.ga.trackException works. I am able to see caught exceptions in GA.)
Thanks

**Comment by victorsosa** [comment]
> But no crash reports showing up in Google Analytics.

Can you post an image of how this report on GA should look like? to get to see more clear you issue.

**Comment by pattnayakpratik93** [comment]
Hi,
In window.ga.trackException('Description', Fatal) , what should i put in Description?

**Comment by pattnayakpratik93** [comment]
@victorsosa 
Can you please help me to integrate 
window.ga.addTransaction('ID', 'Affiliation', Revenue, Tax, Shipping, 'Currency Code')
window.ga.addTransactionItem('ID', 'Name', 'SKU', 'Category', Price, Quantity, 'Currency Code')
These two thing in my ionic app.
Thanks in advance.

**Comment by victorsosa** [comment]
@pattnayakpratik93 you can use any string on description.

of course is product id, name, etc.

**Comment by victorsosa** [comment]
@pattnayakpratik93 there is a new ecommerce API; can you help us test it? checkout the branch ecomerce

**Comment by pattnayakpratik93** [comment]
@victorsosa  For Exception suppose my app crashes on a particular screen or while payment so i have to give like ("Screen name", Fatal)? am i right?

**Comment by pattnayakpratik93** [comment]
@victorsosa And i could not find "branch ecomerce"! could you help me locate it?

**Comment by victorsosa** [comment]
@pattnayakpratik93 yes on description

banches
https://github.com/danwilson/google-analytics-plugin/branches

**Comment by pattnayakpratik93** [comment]
@victorsosa thanks a ton
Can you just guide me how i can add updated API in my code this to my code?

**Comment by victorsosa** [comment]
cordova plugin add https://github.com/danwilson/google-analytics-plugin.git#ecommerce

**Comment by pattnayakpratik93** [comment]
@victorsosa while using the above lines i am getting error
Error: Failed to fetch plugin https://github.com/danwilson/google-analytics-plug
in.git#ecommerce via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: cmd: Command failed with exit code 1 Error output:
npm WARN addRemoteGit Error: not found: git
npm WARN addRemoteGit     at getNotFoundError (C:\Program Files\nodejs\node_modu
les\npm\node_modules\which\which.js:13:12)
npm WARN addRemoteGit     at F (C:\Program Files\nodejs\node_modules\npm\node_mo
dules\which\which.js:68:19)
npm WARN addRemoteGit     at E (C:\Program Files\nodejs\node_modules\npm\node_mo
dules\which\which.js:80:29)
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modul
es\which\which.js:89:16
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modul
es\which\node_modules\isexe\index.js:44:5
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modul
es\which\node_modules\isexe\windows.js:29:5
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modul
es\graceful-fs\polyfills.js:284:29
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:114:15)
npm WARN addRemoteGit  git+https://github.com/danwilson/google-analytics-plugin.
git#ecommerce resetting remote C:\Users\pratik_pattanayak\AppData\Roaming\npm-ca
che\_git-remotes\git-https-github-com-danwilson-google-analytics-plugin-git-ecom
merce-8822cf16 because of error: { Error: not found: git
npm WARN addRemoteGit     at getNotFoundError (C:\Program Files\nodejs\node_modu
les\npm\node_modules\which\which.js:13:12)
npm WARN addRemoteGit     at F (C:\Program Files\nodejs\node_modules\npm\node_mo
dules\which\which.js:68:19)
npm WARN addRemoteGit     at E (C:\Program Files\nodejs\node_modules\npm\node_mo
dules\which\which.js:80:29)
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modul
es\which\which.js:89:16
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modul
es\which\node_modules\isexe\index.js:44:5
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modul
es\which\node_modules\isexe\windows.js:29:5
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modul
es\graceful-fs\polyfills.js:284:29
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:114:15) code: 'ENOGIT'
}
npm ERR! git clone --template=C:\Users\pratik_pattanayak\AppData\Roaming\npm-cac
he\_git-remotes\_templates --mirror https://github.com/danwilson/google-analytic
s-plugin.git C:\Users\pratik_pattanayak\AppData\Roaming\npm-cache\_git-remotes\g
it-https-github-com-danwilson-google-analytics-plugin-git-ecommerce-8822cf16: un
defined
npm ERR! git clone --template=C:\Users\pratik_pattanayak\AppData\Roaming\npm-cac
he\_git-remotes\_templates --mirror https://github.com/danwilson/google-analytic
s-plugin.git C:\Users\pratik_pattanayak\AppData\Roaming\npm-cache\_git-remotes\g
it-https-github-com-danwilson-google-analytics-plugin-git-ecommerce-8822cf16: un
defined
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "https://github.com/danwilson/goog
le-analytics-plugin.git#ecommerce" "--save"
npm ERR! node v7.8.0
npm ERR! npm  v4.2.0
npm ERR! code ENOGIT

npm ERR! not found: git
npm ERR!
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\pratik_pattanayak\AppData\Roaming\npm-cache\_logs\2017-08-
03T16_21_32_631Z-debug.log

**Comment by victorsosa** [comment]
@pattnayakpratik93  yes you have to remove the old plugin.
also please use cordova 1.6.5 (cordova 1.7.x has issue with git urls)

**Comment by pattnayakpratik93** [comment]
when i typed cordova -v in cmd it shows 7.0.1, will the plugin work if not how can i degrade to required version?
