### ISSUE TITLE
Slow and inaccurate?

### ISSUE THREAD

**Issue by profmugshot** [danwilson/google-analytics-plugin#33]
The plugin works!
However, when I test it on Note II Android 4.4 and IOS7 emulator, the GA realtime stat has very long refresh lag: the pages I test shows up on GA after 1~15 minutes. Because of this lag, some pages I visit are not registered.

I have no idea if this is something I did wrong, or is everyone else having this problem?

**Comment by pchop2** [comment]
I don't know of this will contribute to the root cause, but I have, oddly, noticed that this plugin works great on iOS, but android is having a difficult time sending the hits out of the app.  This is the console output I am getting repeatedly as I jump to different views:

```
01-27 15:58:13.912    4250-4529/com.example.app V/GAV3﹕ Thread[GAThread,5,main]: putHit called
01-27 15:58:13.922    4250-4529/com.example.app V/GAV3﹕ Thread[GAThread,5,main]: Sending hit to service   PATH: https:  PARAMS: v=1,  ul=en-us,  t=appview,  ht=1422392293925,  sr=1080x1920,  an=Example,  tid=UA-123456789-6,  aid=com.example.app,  cid=d1873b0c-1994-4497-9bdb-561b444535e7,  av=1.0.0,  _u=.r3oK-AL,  cd=651226 - Title of view,
01-27 15:58:13.932    4250-4332/com.example.app W/PluginManager﹕ THREAD WARNING: exec() call to UniversalAnalytics.trackView blocked the main thread for 20ms. Plugin should use CordovaInterface.getThreadPool().
```

This is what I get when I initiate the app:

```
01-27 15:49:02.344    4250-4529/com.example.app V/GAV3﹕ Thread[GAThread,5,main]: connecting to Analytics service
01-27 15:49:02.354    4250-4529/com.example.app V/GAV3﹕ Thread[GAThread,5,main]: connect: bindService returned true for Intent { act=com.google.android.gms.analytics.service.START cmp=com.google.android.gms/.analytics.service.AnalyticsService (has extras) }
01-27 15:49:02.354    4250-4529/com.example.app V/GAV3﹕ Thread[GAThread,5,main]: Loaded clientId
01-27 15:49:02.354    4250-4529/com.example.app I/GAV3﹕ Thread[GAThread,5,main]: No campaign data found.
01-27 15:49:02.354    4250-4529/com.example.app V/GAV3﹕ Thread[GAThread,5,main]: putHit called
```

Note: I did replace the domain name with 'example' in each log entry.

When I come back from a soda break, I sometimes see the results in my console (so I think it's either heavily delayed or network connectivity is pretty slow).  Just my observations, though.  There may be a chance it might be platform specific, too.

**Comment by paishin** [comment]
Did anyone find a solution to this, my app's analytics seem to be a hit or miss, cant be used reliably

**Comment by adam-back** [comment]
Bump. +1 for slow Android.

**Comment by TompiT** [comment]
I'm using the PlugIn v0.8.0 and I'm currently experiencing the same issue with Android (i.e. Real-Time doesn't work on GA). I can also confirm that it's working fine with iOS. 

According to my investigation I did a small change on the PlugIn class UniversalAnalyticsPlugin. 
I changed the method StartTracker by adding a call to [reportActivityStart](https://developers.google.com/android/reference/com/google/android/gms/analytics/GoogleAnalytics#reportActivityStart%28android.app.Activity%29) like this:
```
    private void startTracker(String id, CallbackContext callbackContext) {
        if (null != id && id.length() > 0) {
            tracker = GoogleAnalytics.getInstance(this.cordova.getActivity()).newTracker(id);
            callbackContext.success("tracker started");
            trackerStarted = true;
            GoogleAnalytics.getInstance(this.cordova.getActivity()).setLocalDispatchPeriod(30);
            GoogleAnalytics.getInstance(this).reportActivityStart(this);
        } else {
            callbackContext.error("tracker id is not valid");
        }
    }
```
By updating the project with this changes the Real-Time is now working on GA.

**Comment by gobalistik** [comment]
Thanks TompiT.  Couldn't get reportActivityStart to compile but it did lead me to the right place.

I changed the time period of the setLocalDispatchPeriod method to 1 minute instead of 30.  It appears to store tracking in local storage and then dispatches it to GA every xx minutes.  Not sure what happens if the app is closed before the time period expires, so if it was set to 30 minutes and I closed my app after 29 would the local storage be cleared and nothing sent to GA?  Any how, changing it to 1 minute I get all the real time stats in GA.

https://developers.google.com/analytics/devguides/collection/android/v3/dispatch

**Comment by RonCan** [comment]
Hey I'm getting `W/CordovaPlugin(14449): Attempted to send a second callback for ID: UniversalAnalytics1642342977` for some reason everytime I leave and come back to the page being tracked. Any ideas?

**Comment by joelmeijering** [comment]
Adding the following to your AndroidManifest.xml' <application> tag could increase reliability:

	    
		<receiver android:name="com.google.android.gms.analytics.AnalyticsReceiver"
		    android:enabled="true">
		    <intent-filter>
		        <action android:name="com.google.android.gms.analytics.ANALYTICS_DISPATCH" />
		    </intent-filter>
		</receiver>
		 
		
		<service android:name="com.google.android.gms.analytics.CampaignTrackingService" />
		<receiver android:name="com.google.android.gms.analytics.CampaignTrackingReceiver"
		          android:exported="true"
		          android:permission="android.permission.INSTALL_PACKAGES">
		  <intent-filter>
		    <action android:name="com.android.vending.INSTALL_REFERRER" />
		  </intent-filter>
		</receiver>
		 
		<service android:name="com.google.android.gms.analytics.AnalyticsService"
		    android:enabled="true"
		    android:exported="false"/>

**Comment by joelmeijering** [comment]
@gobalistik  Your fix worked for me, it caused my android events to show up in real-time reports.

Changing setLocalDispatchPeriod(30) to setLocalDispatchPeriod(1) in UniversalAnalyticsPlugin.java in method startTracker() did the trick.

**Comment by albertleao** [comment]
Is this fix going to be put in the main plugin?

**Comment by victorsosa** [comment]
this was fixed
