### ISSUE TITLE
window.ga.trackMetric not working

### ISSUE THREAD

**Issue by ap0894** [danwilson/google-analytics-plugin#436]
I have an iOS Cordova (v6.4.0) app using this plugin (v1.8.2) & have validated that data is flowing through to Google Analytics.

The issue is I am not seeing any data flowing for my **custom metric**. I am trying to track this with the following:

`window.ga.trackMetric('metric2', highestLevel);`

I have turned debug mode on but I am not seeing any hit getting fired for this. Debug mode is reporting hits for all other `trackView()` calls but nothing for `trackMetric()`.

Testing is being done on iOS simulator on MacBook. As I mentioned all is okay for the page views which are firing but nothing for the custom metric.

**Comment by spacepope** [comment]
On iOS trackMetric() is more like adding metadata to the tracker object, so that the custom metric is attached to the following hits sent.

See [my comment in issue 424](https://github.com/danwilson/google-analytics-plugin/issues/424)..

So you should see a debug output with your custom metric on a following call to trackView or trackEvent. (look at the `cd<metrics index>` entry of the json response..)
If that is not the case, there could be a potential type problem: the doc of the javascript plugin method defines the key parameter as a string, whereas the google analytics api needs a decimal number key.
Please try if the following is working on iOS:
```javascript
window.ga.trackMetric("2", highestLevel);

// If you are using plain javascript and no typescript you could even try
// window.ga.trackMetric(2, highestLevel);
```

For a future release i would propose to change the parameter in the typescript definition and of course the documentation to ```key: number```. But this again would be a breaking change for existing projects..

**Comment by spacepope** [comment]
Just noticed, that i had not the latest master commits in my fork, so i removed my comment about the proposal of changing the Typescript definition of trackMetric to a numeric key, because that's already done.

**Comment by victorsosa** [comment]
It should be like:
`window.ga.trackMetric(2, highestLevel);`

both parameter are numeric
