### ISSUE TITLE
Amazon Fire-OS

### ISSUE THREAD

**Issue by ZZareyan** [danwilson/google-analytics-plugin#85]
Does this wonderful plugin work on amazon fire-os platform???

**Comment by danwilson** [comment]
The Android portion relies on Google Play Services, which is unavailable to Amazon FireOS. So I believe this would not work... though you could try an earlier version of this plugin that use Android Google Analytics v3 instead of v4 (when the switch to Google Play Services happened) to see if that works.

**Comment by ZZareyan** [comment]
Thanks
